### ISSUE TITLE
[Bug] Stacking uniforms.

### ISSUE THREAD

**Issue by NunoSempere** [foretold-app/widedomain#32]
In widedomain, doing mm(uniform(10, 40), uniform(20, 30)) does not do what I'd expect (stack two uniforms one on top of another), but instead just presents one uniform from 20 to 30.

Ozzie Gooen:
> The main part is fine, this is a problem with the visualization

**Comment by OAGr** [comment]
I'm quite sure the problem here is in the d3; the min is showing at the bottom of the y-axis, while really that should be set to 0.

**Comment by NunoSempere** [comment]
So a part of this is that in the multimodal aggregate distribution, points are repeated. 

This can be found out by adding some code to my integrateContinuousShape function (in XYShape.re), which iterates over the points.

```reason
  let integrateContinuousShape =
      (
        ~indefiniteIntegralStepwise=(p, h1) => h1 *. p,
        ~indefiniteIntegralLinear=(p, a, b) => a *. p +. b *. p ** 2.0 /. 2.0,
        t: DistTypes.continuousShape,
      )
      : float => {
    let xs = t.xyShape.xs;
    let ys = t.xyShape.ys;

    E.A.reducei(
      xs,
      0.0,
      (acc, _x, i) => {
        let areaUnderIntegral =
          switch (t.interpolation, i) {
          | (_, 0) => 0.0
          | (`Stepwise, _) =>
            indefiniteIntegralStepwise(xs[i], ys[i - 1])
            -. indefiniteIntegralStepwise(xs[i - 1], ys[i - 1])
          | (`Linear, _) =>
            let x1 = xs[i - 1];
            let x2 = xs[i];
            let h1 = ys[i - 1];
            let h2 = ys[i];
            let b = (h1 -. h2) /. (x1 -. x2);
            let a = h1 -. b *. x1;

            if (Js.Float.isNaN(a)) {
              Js.log("Error, repeated (x,y): ");
              Js.log("x1: " ++ Js.Float.toString(x1));
              Js.log("x2: " ++ Js.Float.toString(x2));
              Js.log("h1: " ++ Js.Float.toString(h1));
              Js.log("h2: " ++ Js.Float.toString(h2));
            };

            indefiniteIntegralLinear(x2, a, b)
            -. indefiniteIntegralLinear(x1, a, b);
          };
        acc +. areaUnderIntegral;
      },
    );
  };

```

If I do that, I get a lot of repeated points:

![Repeated (x,y)](https://user-images.githubusercontent.com/16527456/80413514-dddbd180-88cf-11ea-846d-66ca73bce573.png)

Note that the mean and variance don't work, because they have a division by 0 error. 

The fix would not be difficult (just skip repeated points, or do a first pass and delete them). But why do we have repeated points in the first place?

**Comment by skosch** [comment]
I think fixing how x-points are selected for uniforms has taken care of this issue. Here is what I see:
![image](https://user-images.githubusercontent.com/554383/83910244-14063f80-a71f-11ea-897b-179d3cdfedac.png)

**Comment by NunoSempere** [comment]
Cheers, it seems like this has been solved now; closing the issue.
