### ISSUE TITLE
Truncate doesn't seem to work

### ISSUE THREAD

**Issue by OAGr** [foretold-app/widedomain#56]
I may have broke this.

<img width="1658" alt="image" src="https://user-images.githubusercontent.com/377065/86624859-fe08ca80-bfbb-11ea-9cdd-4b4464f51b19.png">

**Comment by OAGr** [comment]
I realized that [this commit](https://github.com/foretold-app/widedomain/pull/46/commits/c424feaa12d743d9f8397f85c8b5b02822937dfe) wasn't carried over to the epic branch. I tried copying the code in the last 3 commits, but it still doesn't seem to work.

**Comment by skosch** [comment]
I had a sloppy fallthrough branch in a switch. Should be good now!
